# Generated by Django 3.2.6 on 2021-08-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='repeated_count',
        ),
        migrations.AddField(
            model_name='card',
            name='remain_repeated_count',
            field=models.IntegerField(default=6, verbose_name='Количество повторений'),
        ),
    ]
